bot/urls.py
from django.urls import path
from . import views


app_name = "bot"
urlpatterns = [
    path('', views.chat_page, name="chat_page"),
    path('submit/', views.submit_form, name='submit_form'),
    path('clear_chat_history/', views.clear_chat_history, name='clear_chat_history'),
    path('delete_message_from_db/<int:v_id>', views.delete_message_from_db, name="delete_message_from_db"),
    path('update_prompt/', views.update_prompt, name='update_prompt'),
    path('delete_prompt/', views.delete_prompt, name='delete_prompt'),
    


    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('online_people/', views.online_people, name='online_people'),
]

chat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat", include("bot.urls")),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views
from bot import views

admin.site.site_header = "ITC LMS Platformasi"

urlpatterns = [

    # AI bo'limi urllari
    path("chat/", views.chat_page, name="chat_page"),
    path('submit/', include('bot.urls', namespace='bot')),

    path('clear_chat_history/', views.clear_chat_history, name='clear_chat_history'),
    path('delete_message_from_db/<int:v_id>', views.delete_message_from_db, name="delete_message_from_db"),
    path('update_prompt/', views.update_prompt, name='update_prompt'),
    path('delete_prompt/', views.delete_prompt, name='delete_prompt'),
    
    # path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    # path(
    #     "jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")
    # ),  # Django JET dashboard URLS

    # path("blog", include("blog.blogyek.urls")),
    
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("programs/", include("course.urls")),
    path("result/", include("result.urls")),
    path("search/", include("search.urls")),
    path("quiz/", include("quiz.urls")),
    # path("payments/", include("payments.urls")),
    path("accounts/api/", include("accounts.api.urls", namespace="accounts-api")),
    path("admin/", admin.site.urls),
]
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Saxifa topilmadi iltimos tizimni yangilang!")},
        ),
        path("500/", default_views.server_error),
    ]

bot/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class ChatHistory(models.Model):
    username = models.CharField(max_length=200)
    user = models.CharField(max_length=200)
    message = models.TextField()
    datetime = models.DateTimeField(default=timezone.now)


class ChatHistoryBackup(models.Model):
    username = models.CharField(max_length=200)
    user = models.CharField(max_length=200)
    message = models.TextField()
    datetime = models.DateTimeField(default=timezone.now)


class Prompt(models.Model):
    username = models.CharField(max_length=200)
    user = models.CharField(max_length=200)
    message = models.TextField()
    datetime = models.DateTimeField(default=timezone.now)

bot/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class register_form(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Hisob ochish'))

class login_form(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Kirish'))

class send_message(forms.Form):
    message = forms.CharField(widget=forms.Textarea(
        attrs={'autocomplete': 'off', 'class': 'form-control', 'rows': '5', 'style': 'resize: vertical;'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Yuborish'))
        self.helper.form_method = "post"



class prompt_form(forms.ModelForm):
    class Meta:
        model = Prompt
        fields = ['message']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Yangilash'))
        self.helper.form_method = "post"

bot/views.py
from django.shortcuts import render, redirect
from online_users.models import OnlineUserActivity
import markdown
from .models import *
from .forms import *
from .utils import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User


def register_page(request):
    form = register_form()
    if request.method == 'POST':
        form = register_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bot:login')
    context = {'form': form}
    return render(request, 'bot/register.html', context)


def login_page(request):
    form = login_form()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('bot:chat_page')
        else:
            messages.info(request, 'Foydalanuvchi nomi yoki Parol xato...')

    context = {'form': form}
    return render(request, 'bot/login.html', context)


def logout_page(request):
    logout(request)
    return redirect('bot:login')


@staff_member_required
def online_people(request):
    users = User.objects.all()
    online_people = OnlineUserActivity.get_user_activities()
    return render(request, 'bot/online_people.html', {'online_people': online_people, 'users': users})

@staff_member_required
def update_prompt(request):
    current_prompt = Prompt.objects.all().order_by('datetime').first()

    if current_prompt is not None:
        form = prompt_form()
        if request.method == 'POST':
            form = prompt_form(request.POST)
            print(request.POST.get('message'))
            if form.is_valid():
                current_prompt.message = request.POST.get('message')
                current_prompt.save()
                messages.success(request, 'Prompt updated successfully.')
                return redirect('bot:update_prompt')
        context = {'form': form,
                'current_prompt': current_prompt}
    else:
        form = prompt_form()
        if request.method == 'POST':
            form = prompt_form(request.POST)
            print(request.POST.get('message'))
            if form.is_valid():
                Prompt(username='promptUser', user='promptUser', message=request.POST.get('message')).save()
                Prompt(username='promptUser', user='LMS AI', message='OK.').save()
                messages.success(request, 'Prompt created successfully.')
                return redirect('bot:update_prompt')
        context = {'form': form}
        pass
    return render(request, 'bot/update_prompt.html', context)  


@login_required(login_url='bot:login')
def chat_page(request):
    chat_history = ChatHistory.objects.filter(username=request.user.username).order_by('-datetime')
    for row in chat_history:
        md = markdown.Markdown(extensions=["fenced_code", "codehilite"])
        row.message = md.convert(row.message)

    form = send_message()
    data = {'chat_history': chat_history,
            'form': form}
    return render(request, 'bot/chat_page.html', data)


@login_required(login_url='bot:login')
def submit_form(request):
    if request.method == 'POST':
        message = request.POST.get('message')
        messages = []
        if request.user.username != 'admin':
            for chat in Prompt.objects.all().order_by('datetime'):
                if chat.user == 'LMS AI':
                    messages.append({'role': 'model', 'parts': [chat.message]})
                else:
                    messages.append({'role': 'user', 'parts': [chat.message]})
        for chat in ChatHistory.objects.filter(username=request.user.username).order_by('datetime'):
            if chat.user == 'LMS AI':
                messages.append({'role': 'model', 'parts': [chat.message]})
            else:
                messages.append({'role': 'user', 'parts': [chat.message]})
        messages.append({'role': 'user', 'parts': [message]})
        obj = ChatHistory(username=request.user.username,
                          user=''+request.user.username,
                          message=message
                          )
        obj.save()
        bot_yanit = generate_content_bot(messages)
        obj = ChatHistory(username=request.user.username,
                          user='LMS AI',
                          message=bot_yanit
                          )
        obj.save()
        return redirect('bot:chat_page')
    return redirect('bot:chat_page')


@login_required(login_url='bot:login')
def clear_chat_history(request):
    ChatHistory.objects.filter(username=request.user.username).delete()
    return redirect('bot:chat_page')


@login_required(login_url='bot:login')
def delete_message_from_db(request, v_id):
    message = ChatHistory.objects.filter(id=v_id)
    message.delete()
    return redirect('bot:chat_page')


@staff_member_required
def delete_prompt(request):
    prompt_elements = Prompt.objects.all()
    for prompt in prompt_elements:
        prompt.delete()
    return redirect('bot:update_prompt')

bot/templates/bot/chat_page.html
{% extends 'base.html' %}
{% load static %}

{% load humanize %}
{% block content %}


{% load crispy_forms_tags %}

<form method="POST" action="{% url 'bot:submit_form' %}">
{% crispy form %}
</form>

<div id="result"></div>

{% if chat_history %}
    <div class="d-flex justify-content-end">
        <a href="{% url 'bot:clear_chat_history' %}">
            <button type="button" class="btn btn-danger">
                    Chatni tozalash
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-text-fill" viewBox="0 0 16 16">
                      <path d="M16 8c0 3.866-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7M4.5 5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1zm0 2.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1zm0 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1z"/>
                    </svg>
            </button>
        </a>
    </div>

    <div id="chat_hist" data-bs-spy="scroll" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" class="scrollspy-example bg-body-tertiary p-3 rounded-2" tabindex="0">
        {% for chat in chat_history %}
            <div>
                <hr>
                <h5 id="scrollspyHeading1" style="display: inline-block; margin-right: 10px;">
                    {{chat.user}}
                </h5>
                <span class="card-subtitle mb-2 text-body-secondary" style="display: inline-block;">
                    {{chat.datetime | naturaltime}}
                </span>
                <a href="{% url 'bot:delete_message_from_db' v_id=chat.id %}" style="float: right;">
                    <button type="button" class="btn btn-outline-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                            <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                        </svg>
                    </button>
                </a>
            </div>
            <p>
                {{chat.message|safe}}
            </p>
        {% endfor %}
    </div>
{% else %}
    <div data-bs-spy="scroll" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" class="scrollspy-example bg-body-tertiary p-3 rounded-2" tabindex="0">
        <h4>
            <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-arrow-bar-up" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5m-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5"/>
            </svg>
            <i class="bi bi-arrow-bar-up">Chat boshlash uchun xabar yozing!</i>
        </h4>
    </div>
{% endif %}


{% endblock %}


{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Select input field on page load
        window.addEventListener('DOMContentLoaded', function() {
            var messageField = document.getElementById('id_message');
            messageField.focus();
        });
    </script>
{% endblock %}

bot/templates/bot/online_people.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<h1>Online</h1>
<ul>
  {% for user in online_people %}
    <li>{{ user }}</li>
    <li>{{ user.username }}</li>
  {% endfor %}
</ul>

<h1>Users</h1>
<ul>
  {% for user in users %}
    <li>{{ user.username }}</li>
  {% endfor %}
</ul>

{% endblock %}

bot/templates/bot/register.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %}

{% block content %}


{% load crispy_forms_tags %}
<div class="container">
  <div class="row">
    <div class="col-4"></div>
      <div class="col-4">
        <div class="col-12 text-center">
          <h1 class="display-6">Ro'yxatdan o'tish</h1>
        </div>

          {% crispy form %}
      </div>

    <div class="col-4"></div>
  </div>
</div>

{% endblock %}

bot/templates/bot/update_prompt.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% if current_prompt %}
<div id="chat_hist" data-bs-spy="scroll" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" class="scrollspy-example bg-body-tertiary p-3 rounded-2" tabindex="0">
    <div>
        <h5 id="scrollspyHeading1" style="display: inline-block; margin-right: 10px;">
            Current Prompt
        </h5>
        <span class="card-subtitle mb-2 text-body-secondary" style="display: inline-block;">
            Date: {{ current_prompt.datetime }} ({{ current_prompt.datetime | naturaltime }})
        </span>
    </div>
    <p>
        {{ current_prompt.message }}
    </p>
    
</div>

{% else %}
<div id="no-prompt-info" class="alert alert-info">
    There is no prompt available at the moment, every user can talk to Gemini freely.
</div>

{% endif %}

<form method="POST" action="{% url 'bot:update_prompt' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">
        {% if current_prompt %}
            Update Prompt
        {% else %}
            Create Prompt
        {% endif %}
    </button>
</form>

{% if current_prompt %}
<div class="d-flex justify-content-end">
    <a href="{% url 'bot:delete_prompt' %}">
        <button type="button" class="btn btn-danger">
                Delete Prompt
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-text-fill" viewBox="0 0 16 16">
                  <path d="M16 8c0 3.866-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7M4.5 5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1zm0 2.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1zm0 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1z"/>
                </svg>
        </button>
    </a>
</div>
{% endif %}

{% endblock %}