bot/urls.py
from django.urls import path
from . import views


app_name = "bot"
urlpatterns = [
    path('', views.chat_page, name="chat_page"),
    path('submit/', views.submit_form, name='submit_form'),
    path('clear_chat_history/', views.clear_chat_history, name='clear_chat_history'),
    path('delete_message_from_db/<int:v_id>', views.delete_message_from_db, name="delete_message_from_db"),
    path('update_prompt/', views.update_prompt, name='update_prompt'),
    path('delete_prompt/', views.delete_prompt, name='delete_prompt'),
    


    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('online_people/', views.online_people, name='online_people'),
]

chat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat", include("bot.urls")),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views
from bot import views

admin.site.site_header = "ITC LMS Platformasi"

urlpatterns = [

    # AI bo'limi urllari
    path("chat/", views.chat_page, name="chat_page"),
    path('submit/', include('bot.urls', namespace='bot')),

    path('clear_chat_history/', views.clear_chat_history, name='clear_chat_history'),
    path('delete_message_from_db/<int:v_id>', views.delete_message_from_db, name="delete_message_from_db"),
    path('update_prompt/', views.update_prompt, name='update_prompt'),
    path('delete_prompt/', views.delete_prompt, name='delete_prompt'),
    
    # path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    # path(
    #     "jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")
    # ),  # Django JET dashboard URLS

    # path("blog", include("blog.blogyek.urls")),
    
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("programs/", include("course.urls")),
    path("result/", include("result.urls")),
    path("search/", include("search.urls")),
    path("quiz/", include("quiz.urls")),
    # path("payments/", include("payments.urls")),
    path("accounts/api/", include("accounts.api.urls", namespace="accounts-api")),
    path("admin/", admin.site.urls),
]
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Saxifa topilmadi iltimos tizimni yangilang!")},
        ),
        path("500/", default_views.server_error),
    ]

bot/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class ChatHistory(models.Model):
    username = models.CharField(max_length=200)
    user = models.CharField(max_length=200)
    message = models.TextField()
    datetime = models.DateTimeField(default=timezone.now)


class ChatHistoryBackup(models.Model):
    username = models.CharField(max_length=200)
    user = models.CharField(max_length=200)
    message = models.TextField()
    datetime = models.DateTimeField(default=timezone.now)


class Prompt(models.Model):
    username = models.CharField(max_length=200)
    user = models.CharField(max_length=200)
    message = models.TextField()
    datetime = models.DateTimeField(default=timezone.now)

bot/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class register_form(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Hisob ochish'))

class login_form(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Kirish'))

class send_message(forms.Form):
    message = forms.CharField(widget=forms.Textarea(
        attrs={'autocomplete': 'off', 'class': 'form-control', 'rows': '5', 'style': 'resize: vertical;'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Yuborish'))
        self.helper.form_method = "post"



class prompt_form(forms.ModelForm):
    class Meta:
        model = Prompt
        fields = ['message']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Yangilash'))
        self.helper.form_method = "post"

bot/views.py
from django.shortcuts import render, redirect
from online_users.models import OnlineUserActivity
import markdown
from .models import *
from .forms import *
from .utils import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User


def register_page(request):
    form = register_form()
    if request.method == 'POST':
        form = register_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bot:login')
    context = {'form': form}
    return render(request, 'bot/register.html', context)


def login_page(request):
    form = login_form()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('bot:chat_page')
        else:
            messages.info(request, 'Foydalanuvchi nomi yoki Parol xato...')

    context = {'form': form}
    return render(request, 'bot/login.html', context)


def logout_page(request):
    logout(request)
    return redirect('bot:login')


@staff_member_required
def online_people(request):
    users = User.objects.all()
    online_people = OnlineUserActivity.get_user_activities()
    return render(request, 'bot/online_people.html', {'online_people': online_people, 'users': users})

@staff_member_required
def update_prompt(request):
    current_prompt = Prompt.objects.all().order_by('datetime').first()

    if current_prompt is not None:
        form = prompt_form()
        if request.method == 'POST':
            form = prompt_form(request.POST)
            print(request.POST.get('message'))
            if form.is_valid():
                current_prompt.message = request.POST.get('message')
                current_prompt.save()
                messages.success(request, 'Prompt updated successfully.')
                return redirect('bot:update_prompt')
        context = {'form': form,
                'current_prompt': current_prompt}
    else:
        form = prompt_form()
        if request.method == 'POST':
            form = prompt_form(request.POST)
            print(request.POST.get('message'))
            if form.is_valid():
                Prompt(username='promptUser', user='promptUser', message=request.POST.get('message')).save()
                Prompt(username='promptUser', user='LMS AI', message='OK.').save()
                messages.success(request, 'Prompt created successfully.')
                return redirect('bot:update_prompt')
        context = {'form': form}
        pass
    return render(request, 'bot/update_prompt.html', context)  


@login_required(login_url='bot:login')
def chat_page(request):
    chat_history = ChatHistory.objects.filter(username=request.user.username).order_by('-datetime')
    for row in chat_history:
        md = markdown.Markdown(extensions=["fenced_code", "codehilite"])
        row.message = md.convert(row.message)

    form = send_message()
    data = {'chat_history': chat_history,
            'form': form}
    return render(request, 'bot/chat_page.html', data)


@login_required(login_url='bot:login')
def submit_form(request):
    if request.method == 'POST':
        message = request.POST.get('message')
        messages = []
        if request.user.username != 'admin':
            for chat in Prompt.objects.all().order_by('datetime'):
                if chat.user == 'LMS AI':
                    messages.append({'role': 'model', 'parts': [chat.message]})
                else:
                    messages.append({'role': 'user', 'parts': [chat.message]})
        for chat in ChatHistory.objects.filter(username=request.user.username).order_by('datetime'):
            if chat.user == 'LMS AI':
                messages.append({'role': 'model', 'parts': [chat.message]})
            else:
                messages.append({'role': 'user', 'parts': [chat.message]})
        messages.append({'role': 'user', 'parts': [message]})
        obj = ChatHistory(username=request.user.username,
                          user=''+request.user.username,
                          message=message
                          )
        obj.save()
        bot_yanit = generate_content_bot(messages)
        obj = ChatHistory(username=request.user.username,
                          user='LMS AI',
                          message=bot_yanit
                          )
        obj.save()
        return redirect('bot:chat_page')
    return redirect('bot:chat_page')


@login_required(login_url='bot:login')
def clear_chat_history(request):
    ChatHistory.objects.filter(username=request.user.username).delete()
    return redirect('bot:chat_page')


@login_required(login_url='bot:login')
def delete_message_from_db(request, v_id):
    message = ChatHistory.objects.filter(id=v_id)
    message.delete()
    return redirect('bot:chat_page')


@staff_member_required
def delete_prompt(request):
    prompt_elements = Prompt.objects.all()
    for prompt in prompt_elements:
        prompt.delete()
    return redirect('bot:update_prompt')

bot/templates/partials/_footer.html
<footer>
    <div class = "footer py-3 mt-3">
        <div class="container">
            <span class="text-muted">
            </span>
        </div>
    </div>
</footer>

bot/templates/partials/_navbar.html
{% load static %}
<header>
    <div class="navbar navbar-expand-sm navbar-light bg-light">

        <div class="container">
           <a class="navbar-brand" href="{% url 'bot:chat_page' %}">
<!--              <img src="{% static '/img/logo.png' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">-->
               <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-robot" viewBox="0 0 16 16">
              <path d="M6 12.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5M3 8.062C3 6.76 4.235 5.765 5.53 5.886a26.6 26.6 0 0 0 4.94 0C11.765 5.765 13 6.76 13 8.062v1.157a.93.93 0 0 1-.765.935c-.845.147-2.34.346-4.235.346s-3.39-.2-4.235-.346A.93.93 0 0 1 3 9.219zm4.542-.827a.25.25 0 0 0-.217.068l-.92.9a25 25 0 0 1-1.871-.183.25.25 0 0 0-.068.495c.55.076 1.232.149 2.02.193a.25.25 0 0 0 .189-.071l.754-.736.847 1.71a.25.25 0 0 0 .404.062l.932-.97a25 25 0 0 0 1.922-.188.25.25 0 0 0-.068-.495c-.538.074-1.207.145-1.98.189a.25.25 0 0 0-.166.076l-.754.785-.842-1.7a.25.25 0 0 0-.182-.135"/>
              <path d="M8.5 1.866a1 1 0 1 0-1 0V3h-2A4.5 4.5 0 0 0 1 7.5V8a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1v1a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-1a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1v-.5A4.5 4.5 0 0 0 10.5 3h-2zM14 7.5V13a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V7.5A3.5 3.5 0 0 1 5.5 4h5A3.5 3.5 0 0 1 14 7.5"/>
            </svg>
           </a>

            {% if user.is_authenticated %}
            <ul class = "navbar-nav ml-auto">
                <li>
                    <span class = "nav-link"> Salom {{user.username}}! </span>
                </li>
            </ul>
            {% endif %}

            <ul class = "navbar-nav ml-auto">
                {% if user.is_authenticated %}
                {% else %}
                {% endif %}
                {% if user.is_authenticated %}
                {% else %}
                <li>
                    <a href="{% url 'bot:login' %}" class = "nav-link"> Login </a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                {% else %}
                <li>
                    <a href="{% url 'bot:register' %}" class = "nav-link"> Register </a>
                </li>
                {% endif %}



                {% if user.is_staff %}
                    <li>
                        <a href="{% url 'bot:online_people' %}" class = "nav-link"> Online People </a>
                    </li>
                    <li>
                        <a href="{% url 'bot:update_prompt' %}" class = "nav-link"> Update Prompt </a>
                    </li>
                    <li>
                        <a href="{% url 'admin:index' %}" class = "nav-link"> Admin </a>
                    </li>

                {% endif %}

                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'bot:logout' %}" class = "nav-link"> Logout </a>
                </li>
                {% else %}
                {% endif %}

           </ul>
        </div>
    </div>
</header>